#!/usr/bin/env python
# Copyright (C) 2014 by Brian Neal.
# This file is part of purple, the PURPLE (Cipher Machine 97) simulation.
# purple is released under the MIT License (see LICENSE.txt).

import purple.main

purple.main.main()
